# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MeasurementTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MeasurementTab.setGeometry(QtCore.QRect(430, 20, 561, 451))
        self.MeasurementTab.setObjectName("MeasurementTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter_16 = QtWidgets.QSplitter(self.tab)
        self.splitter_16.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.Start_general = QtWidgets.QPushButton(self.splitter_16)
        self.Start_general.setObjectName("Start_general")
        self.Stop_general = QtWidgets.QPushButton(self.splitter_16)
        self.Stop_general.setObjectName("Stop_general")
        self.splitter_8 = QtWidgets.QSplitter(self.tab)
        self.splitter_8.setGeometry(QtCore.QRect(0, 20, 531, 231))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.GateVbox = QtWidgets.QGroupBox(self.splitter_8)
        self.GateVbox.setObjectName("GateVbox")
        self.GateTab = QtWidgets.QTabWidget(self.GateVbox)
        self.GateTab.setGeometry(QtCore.QRect(0, 20, 531, 81))
        self.GateTab.setObjectName("GateTab")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.splitter_9 = QtWidgets.QSplitter(self.tab_7)
        self.splitter_9.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label = QtWidgets.QLabel(self.splitter_9)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.splitter_9)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_2 = QtWidgets.QLabel(self.splitter_9)
        self.label_2.setObjectName("label_2")
        self.GateTab.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.splitter_31 = QtWidgets.QSplitter(self.tab_8)
        self.splitter_31.setGeometry(QtCore.QRect(20, 20, 421, 20))
        self.splitter_31.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_31.setObjectName("splitter_31")
        self.label_26 = QtWidgets.QLabel(self.splitter_31)
        self.label_26.setObjectName("label_26")
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.label_27 = QtWidgets.QLabel(self.splitter_31)
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.label_28 = QtWidgets.QLabel(self.splitter_31)
        self.label_28.setObjectName("label_28")
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.GateTab.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.splitter_33 = QtWidgets.QSplitter(self.tab_9)
        self.splitter_33.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.splitter_33.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_33.setObjectName("splitter_33")
        self.label_32 = QtWidgets.QLabel(self.splitter_33)
        self.label_32.setObjectName("label_32")
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.doubleSpinBox_22.setDecimals(3)
        self.doubleSpinBox_22.setMinimum(-99.999)
        self.doubleSpinBox_22.setMaximum(99.999)
        self.doubleSpinBox_22.setSingleStep(0.1)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.label_33 = QtWidgets.QLabel(self.splitter_33)
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.doubleSpinBox_23.setDecimals(3)
        self.doubleSpinBox_23.setMinimum(-99.999)
        self.doubleSpinBox_23.setMaximum(99.999)
        self.doubleSpinBox_23.setSingleStep(0.1)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.label_34 = QtWidgets.QLabel(self.splitter_33)
        self.label_34.setObjectName("label_34")
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.doubleSpinBox_24.setDecimals(3)
        self.doubleSpinBox_24.setMinimum(-99.999)
        self.doubleSpinBox_24.setMaximum(99.999)
        self.doubleSpinBox_24.setSingleStep(0.1)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.label_36 = QtWidgets.QLabel(self.splitter_33)
        self.label_36.setObjectName("label_36")
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.doubleSpinBox_25.setDecimals(3)
        self.doubleSpinBox_25.setMinimum(-99.999)
        self.doubleSpinBox_25.setMaximum(99.999)
        self.doubleSpinBox_25.setSingleStep(0.1)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.label_35 = QtWidgets.QLabel(self.splitter_33)
        self.label_35.setObjectName("label_35")
        self.spinBox_3 = QtWidgets.QSpinBox(self.splitter_33)
        self.spinBox_3.setObjectName("spinBox_3")
        self.GateTab.addTab(self.tab_9, "")
        self.DrainVbox = QtWidgets.QGroupBox(self.splitter_8)
        self.DrainVbox.setObjectName("DrainVbox")
        self.GateTab_2 = QtWidgets.QTabWidget(self.DrainVbox)
        self.GateTab_2.setGeometry(QtCore.QRect(0, 20, 531, 91))
        self.GateTab_2.setObjectName("GateTab_2")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.splitter_11 = QtWidgets.QSplitter(self.tab_12)
        self.splitter_11.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label_24 = QtWidgets.QLabel(self.splitter_11)
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.splitter_11)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.label_25 = QtWidgets.QLabel(self.splitter_11)
        self.label_25.setObjectName("label_25")
        self.GateTab_2.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.splitter_32 = QtWidgets.QSplitter(self.tab_13)
        self.splitter_32.setGeometry(QtCore.QRect(20, 20, 421, 20))
        self.splitter_32.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_32.setObjectName("splitter_32")
        self.label_29 = QtWidgets.QLabel(self.splitter_32)
        self.label_29.setObjectName("label_29")
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.label_30 = QtWidgets.QLabel(self.splitter_32)
        self.label_30.setObjectName("label_30")
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.label_31 = QtWidgets.QLabel(self.splitter_32)
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.GateTab_2.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.splitter_34 = QtWidgets.QSplitter(self.tab_14)
        self.splitter_34.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.splitter_34.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_34.setObjectName("splitter_34")
        self.label_37 = QtWidgets.QLabel(self.splitter_34)
        self.label_37.setObjectName("label_37")
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.doubleSpinBox_26.setDecimals(3)
        self.doubleSpinBox_26.setMinimum(-99.999)
        self.doubleSpinBox_26.setMaximum(99.999)
        self.doubleSpinBox_26.setSingleStep(0.1)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.label_38 = QtWidgets.QLabel(self.splitter_34)
        self.label_38.setObjectName("label_38")
        self.doubleSpinBox_27 = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.doubleSpinBox_27.setDecimals(3)
        self.doubleSpinBox_27.setMinimum(-99.999)
        self.doubleSpinBox_27.setMaximum(99.999)
        self.doubleSpinBox_27.setSingleStep(0.1)
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.label_39 = QtWidgets.QLabel(self.splitter_34)
        self.label_39.setObjectName("label_39")
        self.doubleSpinBox_28 = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.doubleSpinBox_28.setDecimals(3)
        self.doubleSpinBox_28.setMinimum(-99.999)
        self.doubleSpinBox_28.setMaximum(99.999)
        self.doubleSpinBox_28.setSingleStep(0.1)
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.label_40 = QtWidgets.QLabel(self.splitter_34)
        self.label_40.setObjectName("label_40")
        self.doubleSpinBox_29 = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.doubleSpinBox_29.setDecimals(3)
        self.doubleSpinBox_29.setMinimum(-99.999)
        self.doubleSpinBox_29.setMaximum(99.999)
        self.doubleSpinBox_29.setSingleStep(0.1)
        self.doubleSpinBox_29.setObjectName("doubleSpinBox_29")
        self.label_41 = QtWidgets.QLabel(self.splitter_34)
        self.label_41.setObjectName("label_41")
        self.spinBox_4 = QtWidgets.QSpinBox(self.splitter_34)
        self.spinBox_4.setObjectName("spinBox_4")
        self.GateTab_2.addTab(self.tab_14, "")
        self.MeasurementTab.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.splitter_13 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_13.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.Start_resistance = QtWidgets.QPushButton(self.splitter_13)
        self.Start_resistance.setObjectName("Start_resistance")
        self.Stop_resistance = QtWidgets.QPushButton(self.splitter_13)
        self.Stop_resistance.setObjectName("Stop_resistance")
        self.splitter_10 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_10.setGeometry(QtCore.QRect(0, 20, 541, 231))
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName("splitter_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_10)
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter_12 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_12.setGeometry(QtCore.QRect(10, 30, 456, 20))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.label_3 = QtWidgets.QLabel(self.splitter_12)
        self.label_3.setObjectName("label_3")
        self.spinbox_res_Vdstart = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdstart.setDecimals(3)
        self.spinbox_res_Vdstart.setMinimum(-99.999)
        self.spinbox_res_Vdstart.setMaximum(99.999)
        self.spinbox_res_Vdstart.setSingleStep(0.1)
        self.spinbox_res_Vdstart.setProperty("value", 0.0)
        self.spinbox_res_Vdstart.setObjectName("spinbox_res_Vdstart")
        self.label_43 = QtWidgets.QLabel(self.splitter_12)
        self.label_43.setObjectName("label_43")
        self.spinbox_res_Vdmax = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdmax.setDecimals(3)
        self.spinbox_res_Vdmax.setMinimum(-99.999)
        self.spinbox_res_Vdmax.setMaximum(99.999)
        self.spinbox_res_Vdmax.setSingleStep(0.1)
        self.spinbox_res_Vdmax.setProperty("value", 0.2)
        self.spinbox_res_Vdmax.setObjectName("spinbox_res_Vdmax")
        self.label_4 = QtWidgets.QLabel(self.splitter_12)
        self.label_4.setObjectName("label_4")
        self.spinbox_res_Vdmin = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdmin.setDecimals(3)
        self.spinbox_res_Vdmin.setMinimum(-99.999)
        self.spinbox_res_Vdmin.setMaximum(99.999)
        self.spinbox_res_Vdmin.setSingleStep(0.1)
        self.spinbox_res_Vdmin.setProperty("value", -0.2)
        self.spinbox_res_Vdmin.setObjectName("spinbox_res_Vdmin")
        self.label_5 = QtWidgets.QLabel(self.splitter_12)
        self.label_5.setObjectName("label_5")
        self.spinbox_res_Vdstep = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdstep.setDecimals(3)
        self.spinbox_res_Vdstep.setMinimum(-99.999)
        self.spinbox_res_Vdstep.setMaximum(99.999)
        self.spinbox_res_Vdstep.setSingleStep(0.01)
        self.spinbox_res_Vdstep.setProperty("value", 0.05)
        self.spinbox_res_Vdstep.setObjectName("spinbox_res_Vdstep")
        self.label_6 = QtWidgets.QLabel(self.splitter_12)
        self.label_6.setObjectName("label_6")
        self.spinbox_res_cycles = QtWidgets.QSpinBox(self.splitter_12)
        self.spinbox_res_cycles.setProperty("value", 2)
        self.spinbox_res_cycles.setObjectName("spinbox_res_cycles")
        self.MeasurementTab.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.splitter_14 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_14.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.Start_transfer = QtWidgets.QPushButton(self.splitter_14)
        self.Start_transfer.setObjectName("Start_transfer")
        self.Stop_transfer = QtWidgets.QPushButton(self.splitter_14)
        self.Stop_transfer.setObjectName("Stop_transfer")
        self.splitter_17 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_17.setGeometry(QtCore.QRect(0, 20, 541, 221))
        self.splitter_17.setOrientation(QtCore.Qt.Vertical)
        self.splitter_17.setObjectName("splitter_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_17)
        self.groupBox_4.setObjectName("groupBox_4")
        self.splitter_19 = QtWidgets.QSplitter(self.groupBox_4)
        self.splitter_19.setGeometry(QtCore.QRect(10, 30, 521, 31))
        self.splitter_19.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_19.setObjectName("splitter_19")
        self.label_7 = QtWidgets.QLabel(self.splitter_19)
        self.label_7.setObjectName("label_7")
        self.Spinbox_Transfer_Vgstart = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgstart.setDecimals(3)
        self.Spinbox_Transfer_Vgstart.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgstart.setMaximum(99.999)
        self.Spinbox_Transfer_Vgstart.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgstart.setObjectName("Spinbox_Transfer_Vgstart")
        self.label_8 = QtWidgets.QLabel(self.splitter_19)
        self.label_8.setObjectName("label_8")
        self.Spinbox_Transfer_Vgmax = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgmax.setDecimals(3)
        self.Spinbox_Transfer_Vgmax.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgmax.setMaximum(99.999)
        self.Spinbox_Transfer_Vgmax.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgmax.setProperty("value", 0.8)
        self.Spinbox_Transfer_Vgmax.setObjectName("Spinbox_Transfer_Vgmax")
        self.label_10 = QtWidgets.QLabel(self.splitter_19)
        self.label_10.setObjectName("label_10")
        self.Spinbox_Transfer_Vgmin = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgmin.setDecimals(3)
        self.Spinbox_Transfer_Vgmin.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgmin.setMaximum(99.999)
        self.Spinbox_Transfer_Vgmin.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgmin.setProperty("value", -0.8)
        self.Spinbox_Transfer_Vgmin.setObjectName("Spinbox_Transfer_Vgmin")
        self.label_9 = QtWidgets.QLabel(self.splitter_19)
        self.label_9.setObjectName("label_9")
        self.Spinbox_Transfer_Vgstep = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgstep.setDecimals(3)
        self.Spinbox_Transfer_Vgstep.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgstep.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgstep.setProperty("value", -0.1)
        self.Spinbox_Transfer_Vgstep.setObjectName("Spinbox_Transfer_Vgstep")
        self.label_11 = QtWidgets.QLabel(self.splitter_19)
        self.label_11.setObjectName("label_11")
        self.Spinbox_Transfer_cycles = QtWidgets.QSpinBox(self.splitter_19)
        self.Spinbox_Transfer_cycles.setProperty("value", 3)
        self.Spinbox_Transfer_cycles.setObjectName("Spinbox_Transfer_cycles")
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter_17)
        self.groupBox_5.setObjectName("groupBox_5")
        self.splitter_20 = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter_20.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.splitter_20.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_20.setObjectName("splitter_20")
        self.label_12 = QtWidgets.QLabel(self.splitter_20)
        self.label_12.setObjectName("label_12")
        self.Spinbox_Transfer_Vd = QtWidgets.QDoubleSpinBox(self.splitter_20)
        self.Spinbox_Transfer_Vd.setDecimals(3)
        self.Spinbox_Transfer_Vd.setMinimum(-99.999)
        self.Spinbox_Transfer_Vd.setMaximum(99.999)
        self.Spinbox_Transfer_Vd.setSingleStep(0.1)
        self.Spinbox_Transfer_Vd.setProperty("value", -0.2)
        self.Spinbox_Transfer_Vd.setObjectName("Spinbox_Transfer_Vd")
        self.MeasurementTab.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.splitter_15 = QtWidgets.QSplitter(self.tab_6)
        self.splitter_15.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.Start_online = QtWidgets.QPushButton(self.splitter_15)
        self.Start_online.setObjectName("Start_online")
        self.Stop_online = QtWidgets.QPushButton(self.splitter_15)
        self.Stop_online.setObjectName("Stop_online")
        self.splitter_18 = QtWidgets.QSplitter(self.tab_6)
        self.splitter_18.setGeometry(QtCore.QRect(0, 20, 181, 231))
        self.splitter_18.setOrientation(QtCore.Qt.Vertical)
        self.splitter_18.setObjectName("splitter_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.splitter_18)
        self.groupBox_6.setObjectName("groupBox_6")
        self.splitter_21 = QtWidgets.QSplitter(self.groupBox_6)
        self.splitter_21.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.splitter_21.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_21.setObjectName("splitter_21")
        self.label_13 = QtWidgets.QLabel(self.splitter_21)
        self.label_13.setObjectName("label_13")
        self.spinbox_vg = QtWidgets.QDoubleSpinBox(self.splitter_21)
        self.spinbox_vg.setWrapping(False)
        self.spinbox_vg.setDecimals(3)
        self.spinbox_vg.setMinimum(-99.999)
        self.spinbox_vg.setMaximum(99.999)
        self.spinbox_vg.setSingleStep(0.1)
        self.spinbox_vg.setProperty("value", -0.5)
        self.spinbox_vg.setObjectName("spinbox_vg")
        self.groupBox_7 = QtWidgets.QGroupBox(self.splitter_18)
        self.groupBox_7.setObjectName("groupBox_7")
        self.splitter_22 = QtWidgets.QSplitter(self.groupBox_7)
        self.splitter_22.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setObjectName("splitter_22")
        self.label_14 = QtWidgets.QLabel(self.splitter_22)
        self.label_14.setObjectName("label_14")
        self.spinbox_vd = QtWidgets.QDoubleSpinBox(self.splitter_22)
        self.spinbox_vd.setProperty("showGroupSeparator", False)
        self.spinbox_vd.setDecimals(3)
        self.spinbox_vd.setMinimum(-99.999)
        self.spinbox_vd.setSingleStep(0.1)
        self.spinbox_vd.setProperty("value", -0.5)
        self.spinbox_vd.setObjectName("spinbox_vd")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setGeometry(QtCore.QRect(190, 20, 271, 231))
        self.groupBox_8.setObjectName("groupBox_8")
        self.proteinBSAtab = QtWidgets.QTabWidget(self.groupBox_8)
        self.proteinBSAtab.setGeometry(QtCore.QRect(10, 30, 251, 181))
        self.proteinBSAtab.setObjectName("proteinBSAtab")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.splitter_29 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_29.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.splitter_29.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_29.setObjectName("splitter_29")
        self.label_21 = QtWidgets.QLabel(self.splitter_29)
        self.label_21.setObjectName("label_21")
        self.combo_BSA = QtWidgets.QComboBox(self.splitter_29)
        self.combo_BSA.setObjectName("combo_BSA")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.splitter_24 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_24.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.splitter_24.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_24.setObjectName("splitter_24")
        self.label_16 = QtWidgets.QLabel(self.splitter_24)
        self.label_16.setObjectName("label_16")
        self.timeBSA = QtWidgets.QTimeEdit(self.splitter_24)
        self.timeBSA.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeBSA.setTime(QtCore.QTime(0, 5, 0))
        self.timeBSA.setObjectName("timeBSA")
        self.splitter_25 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_25.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.splitter_25.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_25.setObjectName("splitter_25")
        self.label_17 = QtWidgets.QLabel(self.splitter_25)
        self.label_17.setObjectName("label_17")
        self.radioButton = QtWidgets.QRadioButton(self.splitter_25)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter_25)
        self.radioButton_2.setObjectName("radioButton_2")
        self.proteinBSAtab.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.splitter_26 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_26.setGeometry(QtCore.QRect(10, 40, 221, 31))
        self.splitter_26.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_26.setObjectName("splitter_26")
        self.label_18 = QtWidgets.QLabel(self.splitter_26)
        self.label_18.setObjectName("label_18")
        self.radioButton_3 = QtWidgets.QRadioButton(self.splitter_26)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.splitter_26)
        self.radioButton_4.setObjectName("radioButton_4")
        self.splitter_27 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_27.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.splitter_27.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_27.setObjectName("splitter_27")
        self.label_19 = QtWidgets.QLabel(self.splitter_27)
        self.label_19.setObjectName("label_19")
        self.timeProtein = QtWidgets.QTimeEdit(self.splitter_27)
        self.timeProtein.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeProtein.setTime(QtCore.QTime(0, 2, 0))
        self.timeProtein.setObjectName("timeProtein")
        self.splitter_28 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_28.setGeometry(QtCore.QRect(10, 100, 221, 31))
        self.splitter_28.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_28.setObjectName("splitter_28")
        self.label_20 = QtWidgets.QLabel(self.splitter_28)
        self.label_20.setObjectName("label_20")
        self.combo_protein = QtWidgets.QComboBox(self.splitter_28)
        self.combo_protein.setObjectName("combo_protein")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.proteinBSAtab.addTab(self.tab_11, "")
        self.MeasurementTab.addTab(self.tab_6, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 421, 451))
        self.groupBox.setObjectName("groupBox")
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_5.setGeometry(QtCore.QRect(10, 30, 371, 61))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.FilePathName = QtWidgets.QLabel(self.splitter_4)
        self.FilePathName.setObjectName("FilePathName")
        self.browseFile = QtWidgets.QToolButton(self.splitter_4)
        self.browseFile.setObjectName("browseFile")
        self.text_filepath = QtWidgets.QTextBrowser(self.splitter_5)
        self.text_filepath.setObjectName("text_filepath")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 200, 301, 91))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.CommentName = QtWidgets.QLabel(self.splitter_3)
        self.CommentName.setObjectName("CommentName")
        self.text_comments = QtWidgets.QTextEdit(self.splitter_3)
        self.text_comments.setObjectName("text_comments")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 300, 401, 61))
        self.groupBox_9.setObjectName("groupBox_9")
        self.splitter_30 = QtWidgets.QSplitter(self.groupBox_9)
        self.splitter_30.setGeometry(QtCore.QRect(10, 20, 381, 31))
        self.splitter_30.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_30.setObjectName("splitter_30")
        self.label_22 = QtWidgets.QLabel(self.splitter_30)
        self.label_22.setObjectName("label_22")
        self.spinbox_Ig_limit = QtWidgets.QDoubleSpinBox(self.splitter_30)
        self.spinbox_Ig_limit.setDecimals(3)
        self.spinbox_Ig_limit.setMaximum(1000.0)
        self.spinbox_Ig_limit.setSingleStep(1)
        self.spinbox_Ig_limit.setProperty("value", 1.0)
        self.spinbox_Ig_limit.setObjectName("spinbox_Ig_limit")
        self.label_23 = QtWidgets.QLabel(self.splitter_30)
        self.label_23.setObjectName("label_23")
        self.spinbox_Id_limit = QtWidgets.QDoubleSpinBox(self.splitter_30)
        self.spinbox_Id_limit.setDecimals(3)
        self.spinbox_Id_limit.setMaximum(1000.0)
        self.spinbox_Id_limit.setSingleStep(1)
        self.spinbox_Id_limit.setProperty("value", 1.0)
        self.spinbox_Id_limit.setObjectName("spinbox_Id_limit")
        self.splitter_6 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_6.setGeometry(QtCore.QRect(10, 100, 301, 91))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtWidgets.QSplitter(self.splitter_6)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.SampleName = QtWidgets.QLabel(self.splitter)
        self.SampleName.setObjectName("SampleName")
        self.text_sample = QtWidgets.QTextEdit(self.splitter)
        self.text_sample.setObjectName("text_sample")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.DeviceName = QtWidgets.QLabel(self.splitter_2)
        self.DeviceName.setObjectName("DeviceName")
        self.text_device = QtWidgets.QTextEdit(self.splitter_2)
        self.text_device.setObjectName("text_device")
        self.splitter_36 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_36.setGeometry(QtCore.QRect(20, 370, 231, 31))
        self.splitter_36.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_36.setObjectName("splitter_36")
        self.label_42 = QtWidgets.QLabel(self.splitter_36)
        self.label_42.setObjectName("label_42")
        self.spinBox_DAQ = QtWidgets.QSpinBox(self.splitter_36)
        self.spinBox_DAQ.setMaximum(1000)
        self.spinBox_DAQ.setProperty("value", 250)
        self.spinBox_DAQ.setObjectName("spinBox_DAQ")
        self.splitter_7 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_7.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_35 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_35.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_35.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_35.setObjectName("splitter_35")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.MeasurementTab.setCurrentIndex(3)
        self.GateTab.setCurrentIndex(2)
        self.GateTab_2.setCurrentIndex(2)
        self.proteinBSAtab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start_general.setText(_translate("MainWindow", "Start"))
        self.Stop_general.setText(_translate("MainWindow", "Stop"))
        self.GateVbox.setTitle(_translate("MainWindow", "Gate Voltage :"))
        self.label.setText(_translate("MainWindow", "Vg : "))
        self.label_2.setText(_translate("MainWindow", "[V]"))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_7), _translate("MainWindow", "Constant"))
        self.label_26.setText(_translate("MainWindow", "Start : "))
        self.label_27.setText(_translate("MainWindow", "Stop :"))
        self.label_28.setText(_translate("MainWindow", "Step :"))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_8), _translate("MainWindow", "Sweep"))
        self.label_32.setText(_translate("MainWindow", "Start : "))
        self.label_33.setText(_translate("MainWindow", "Max : "))
        self.label_34.setText(_translate("MainWindow", "Min :"))
        self.label_36.setText(_translate("MainWindow", "Step : "))
        self.label_35.setText(_translate("MainWindow", "Cycles : "))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_9), _translate("MainWindow", "Cyclic"))
        self.DrainVbox.setTitle(_translate("MainWindow", "Drain Voltage : "))
        self.label_24.setText(_translate("MainWindow", "Vd : "))
        self.label_25.setText(_translate("MainWindow", "[V]"))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_12), _translate("MainWindow", "Constant"))
        self.label_29.setText(_translate("MainWindow", "Start : "))
        self.label_30.setText(_translate("MainWindow", "Stop :"))
        self.label_31.setText(_translate("MainWindow", "Step :"))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_13), _translate("MainWindow", "Sweep"))
        self.label_37.setText(_translate("MainWindow", "Start : "))
        self.label_38.setText(_translate("MainWindow", "Max : "))
        self.label_39.setText(_translate("MainWindow", "Min :"))
        self.label_40.setText(_translate("MainWindow", "Step : "))
        self.label_41.setText(_translate("MainWindow", "Cycles : "))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_14), _translate("MainWindow", "Cyclic"))
        self.MeasurementTab.setTabText(self.MeasurementTab.indexOf(self.tab), _translate("MainWindow", "General"))
        self.Start_resistance.setText(_translate("MainWindow", "Start"))
        self.Stop_resistance.setText(_translate("MainWindow", "Stop"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drain Voltage [V]: "))
        self.label_3.setText(_translate("MainWindow", "Start : "))
        self.label_43.setText(_translate("MainWindow", "Max:"))
        self.label_4.setText(_translate("MainWindow", "Min: "))
        self.label_5.setText(_translate("MainWindow", "Step : "))
        self.label_6.setText(_translate("MainWindow", "Cycles:"))
        self.MeasurementTab.setTabText(self.MeasurementTab.indexOf(self.tab_5), _translate("MainWindow", "Resistance"))
        self.Start_transfer.setText(_translate("MainWindow", "Start"))
        self.Stop_transfer.setText(_translate("MainWindow", "Stop"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Gate Voltage [V] :"))
        self.label_7.setText(_translate("MainWindow", "Start :"))
        self.label_8.setText(_translate("MainWindow", "Max :"))
        self.label_10.setText(_translate("MainWindow", "Min : "))
        self.label_9.setText(_translate("MainWindow", "Step : "))
        self.label_11.setText(_translate("MainWindow", "Cycles :"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Drain Voltage [V] :"))
        self.label_12.setText(_translate("MainWindow", "Constant : "))
        self.MeasurementTab.setTabText(self.MeasurementTab.indexOf(self.tab_2), _translate("MainWindow", "Transfer"))
        self.Start_online.setText(_translate("MainWindow", "Start"))
        self.Stop_online.setText(_translate("MainWindow", "Stop"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gate Voltage [V] :"))
        self.label_13.setText(_translate("MainWindow", "Constant : "))
        self.groupBox_7.setTitle(_translate("MainWindow", "Drain Voltage [V] :"))
        self.label_14.setText(_translate("MainWindow", "Constant : "))
        self.groupBox_8.setTitle(_translate("MainWindow", "Measurement setup :"))
        self.label_21.setText(_translate("MainWindow", "BSA application : "))
        self.combo_BSA.setItemText(0, _translate("MainWindow", "base"))
        self.combo_BSA.setItemText(1, _translate("MainWindow", "1x"))
        self.combo_BSA.setItemText(2, _translate("MainWindow", "2x"))
        self.combo_BSA.setItemText(3, _translate("MainWindow", "3x"))
        self.combo_BSA.setItemText(4, _translate("MainWindow", "4x"))
        self.combo_BSA.setItemText(5, _translate("MainWindow", "5x"))
        self.label_16.setText(_translate("MainWindow", "Measurement Time [mm:ss] : "))
        self.timeBSA.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.label_17.setText(_translate("MainWindow", "Stop if Id < 2% :"))
        self.radioButton.setText(_translate("MainWindow", "Yes"))
        self.radioButton_2.setText(_translate("MainWindow", "No"))
        self.proteinBSAtab.setTabText(self.proteinBSAtab.indexOf(self.tab_10), _translate("MainWindow", "BSA"))
        self.label_18.setText(_translate("MainWindow", "Stop if Id < 2% : "))
        self.radioButton_3.setText(_translate("MainWindow", "Yes"))
        self.radioButton_4.setText(_translate("MainWindow", "No"))
        self.label_19.setText(_translate("MainWindow", "Measurement Time [mm:ss] : "))
        self.timeProtein.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.label_20.setText(_translate("MainWindow", "Protein Concentration : "))
        self.combo_protein.setItemText(0, _translate("MainWindow", "base"))
        self.combo_protein.setItemText(1, _translate("MainWindow", "conc. -12"))
        self.combo_protein.setItemText(2, _translate("MainWindow", "conc. -11"))
        self.combo_protein.setItemText(3, _translate("MainWindow", "conc. -10"))
        self.combo_protein.setItemText(4, _translate("MainWindow", "conc. -9"))
        self.proteinBSAtab.setTabText(self.proteinBSAtab.indexOf(self.tab_11), _translate("MainWindow", "Protein"))
        self.MeasurementTab.setTabText(self.MeasurementTab.indexOf(self.tab_6), _translate("MainWindow", "Online"))
        self.groupBox.setTitle(_translate("MainWindow", "General:"))
        self.FilePathName.setText(_translate("MainWindow", "File Path : "))
        self.browseFile.setText(_translate("MainWindow", "Browse"))
        self.CommentName.setText(_translate("MainWindow", "Comments :"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Limits : "))
        self.label_22.setText(_translate("MainWindow", "Gate Current [mA] : "))
        self.label_23.setText(_translate("MainWindow", "Drain Current [mA] : "))
        self.SampleName.setText(_translate("MainWindow", "Sample :"))
        self.DeviceName.setText(_translate("MainWindow", "Device :"))
        self.label_42.setText(_translate("MainWindow", "DAQ time [ms]"))

