# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Output = QtWidgets.QTabWidget(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(480, 30, 591, 451))
        self.Output.setObjectName("Output")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter_16 = QtWidgets.QSplitter(self.tab)
        self.splitter_16.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.Start_general = QtWidgets.QPushButton(self.splitter_16)
        self.Start_general.setObjectName("Start_general")
        self.Stop_general = QtWidgets.QPushButton(self.splitter_16)
        self.Stop_general.setObjectName("Stop_general")
        self.splitter_8 = QtWidgets.QSplitter(self.tab)
        self.splitter_8.setGeometry(QtCore.QRect(0, 20, 531, 231))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.GateVbox = QtWidgets.QGroupBox(self.splitter_8)
        self.GateVbox.setObjectName("GateVbox")
        self.GateTab = QtWidgets.QTabWidget(self.GateVbox)
        self.GateTab.setGeometry(QtCore.QRect(0, 20, 531, 81))
        self.GateTab.setObjectName("GateTab")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.splitter_9 = QtWidgets.QSplitter(self.tab_7)
        self.splitter_9.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label = QtWidgets.QLabel(self.splitter_9)
        self.label.setObjectName("label")
        self.gen_const_vg = QtWidgets.QDoubleSpinBox(self.splitter_9)
        self.gen_const_vg.setDecimals(2)
        self.gen_const_vg.setMinimum(-99.0)
        self.gen_const_vg.setSingleStep(0.1)
        self.gen_const_vg.setObjectName("gen_const_vg")
        self.label_2 = QtWidgets.QLabel(self.splitter_9)
        self.label_2.setObjectName("label_2")
        self.GateTab.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.splitter_31 = QtWidgets.QSplitter(self.tab_8)
        self.splitter_31.setGeometry(QtCore.QRect(20, 20, 421, 20))
        self.splitter_31.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_31.setObjectName("splitter_31")
        self.label_26 = QtWidgets.QLabel(self.splitter_31)
        self.label_26.setObjectName("label_26")
        self.gen_sweep_start_vg = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.gen_sweep_start_vg.setDecimals(3)
        self.gen_sweep_start_vg.setMinimum(-99.0)
        self.gen_sweep_start_vg.setSingleStep(0.1)
        self.gen_sweep_start_vg.setObjectName("gen_sweep_start_vg")
        self.label_27 = QtWidgets.QLabel(self.splitter_31)
        self.label_27.setObjectName("label_27")
        self.gen_sweep_stop_vg = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.gen_sweep_stop_vg.setDecimals(3)
        self.gen_sweep_stop_vg.setMinimum(-99.0)
        self.gen_sweep_stop_vg.setSingleStep(0.1)
        self.gen_sweep_stop_vg.setObjectName("gen_sweep_stop_vg")
        self.label_28 = QtWidgets.QLabel(self.splitter_31)
        self.label_28.setObjectName("label_28")
        self.gen_sweep_step_vg = QtWidgets.QDoubleSpinBox(self.splitter_31)
        self.gen_sweep_step_vg.setDecimals(3)
        self.gen_sweep_step_vg.setMinimum(-99.0)
        self.gen_sweep_step_vg.setSingleStep(0.1)
        self.gen_sweep_step_vg.setObjectName("gen_sweep_step_vg")
        self.GateTab.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.splitter_33 = QtWidgets.QSplitter(self.tab_9)
        self.splitter_33.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.splitter_33.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_33.setObjectName("splitter_33")
        self.label_32 = QtWidgets.QLabel(self.splitter_33)
        self.label_32.setObjectName("label_32")
        self.gen_cyc_start_vg = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.gen_cyc_start_vg.setDecimals(3)
        self.gen_cyc_start_vg.setMinimum(-99.999)
        self.gen_cyc_start_vg.setMaximum(99.999)
        self.gen_cyc_start_vg.setSingleStep(0.1)
        self.gen_cyc_start_vg.setObjectName("gen_cyc_start_vg")
        self.label_33 = QtWidgets.QLabel(self.splitter_33)
        self.label_33.setObjectName("label_33")
        self.gen_cyc_max_vg = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.gen_cyc_max_vg.setDecimals(3)
        self.gen_cyc_max_vg.setMinimum(-99.999)
        self.gen_cyc_max_vg.setMaximum(99.999)
        self.gen_cyc_max_vg.setSingleStep(0.1)
        self.gen_cyc_max_vg.setProperty("value", 0.8)
        self.gen_cyc_max_vg.setObjectName("gen_cyc_max_vg")
        self.label_34 = QtWidgets.QLabel(self.splitter_33)
        self.label_34.setObjectName("label_34")
        self.gen_cyc_min_vg = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.gen_cyc_min_vg.setDecimals(3)
        self.gen_cyc_min_vg.setMinimum(-99.999)
        self.gen_cyc_min_vg.setMaximum(99.999)
        self.gen_cyc_min_vg.setSingleStep(0.1)
        self.gen_cyc_min_vg.setProperty("value", -0.8)
        self.gen_cyc_min_vg.setObjectName("gen_cyc_min_vg")
        self.label_36 = QtWidgets.QLabel(self.splitter_33)
        self.label_36.setObjectName("label_36")
        self.gen_cyc_step_vg = QtWidgets.QDoubleSpinBox(self.splitter_33)
        self.gen_cyc_step_vg.setDecimals(3)
        self.gen_cyc_step_vg.setMinimum(-99.999)
        self.gen_cyc_step_vg.setMaximum(99.999)
        self.gen_cyc_step_vg.setSingleStep(0.1)
        self.gen_cyc_step_vg.setProperty("value", 0.05)
        self.gen_cyc_step_vg.setObjectName("gen_cyc_step_vg")
        self.label_35 = QtWidgets.QLabel(self.splitter_33)
        self.label_35.setObjectName("label_35")
        self.gen_cycnum_vg = QtWidgets.QSpinBox(self.splitter_33)
        self.gen_cycnum_vg.setProperty("value", 3)
        self.gen_cycnum_vg.setObjectName("gen_cycnum_vg")
        self.GateTab.addTab(self.tab_9, "")
        self.DrainVbox = QtWidgets.QGroupBox(self.splitter_8)
        self.DrainVbox.setObjectName("DrainVbox")
        self.GateTab_2 = QtWidgets.QTabWidget(self.DrainVbox)
        self.GateTab_2.setGeometry(QtCore.QRect(0, 20, 531, 91))
        self.GateTab_2.setObjectName("GateTab_2")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.splitter_11 = QtWidgets.QSplitter(self.tab_12)
        self.splitter_11.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.label_24 = QtWidgets.QLabel(self.splitter_11)
        self.label_24.setObjectName("label_24")
        self.gen_const_vd = QtWidgets.QDoubleSpinBox(self.splitter_11)
        self.gen_const_vd.setMinimum(-99.0)
        self.gen_const_vd.setSingleStep(0.1)
        self.gen_const_vd.setObjectName("gen_const_vd")
        self.label_25 = QtWidgets.QLabel(self.splitter_11)
        self.label_25.setObjectName("label_25")
        self.GateTab_2.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.splitter_32 = QtWidgets.QSplitter(self.tab_13)
        self.splitter_32.setGeometry(QtCore.QRect(20, 20, 421, 20))
        self.splitter_32.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_32.setObjectName("splitter_32")
        self.label_29 = QtWidgets.QLabel(self.splitter_32)
        self.label_29.setObjectName("label_29")
        self.gen_sweep_start_vd = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.gen_sweep_start_vd.setDecimals(3)
        self.gen_sweep_start_vd.setMinimum(-99.0)
        self.gen_sweep_start_vd.setSingleStep(0.1)
        self.gen_sweep_start_vd.setObjectName("gen_sweep_start_vd")
        self.label_30 = QtWidgets.QLabel(self.splitter_32)
        self.label_30.setObjectName("label_30")
        self.gen_sweep_stop_vd = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.gen_sweep_stop_vd.setDecimals(3)
        self.gen_sweep_stop_vd.setMinimum(-99.0)
        self.gen_sweep_stop_vd.setSingleStep(0.1)
        self.gen_sweep_stop_vd.setObjectName("gen_sweep_stop_vd")
        self.label_31 = QtWidgets.QLabel(self.splitter_32)
        self.label_31.setObjectName("label_31")
        self.gen_sweep_step_vd = QtWidgets.QDoubleSpinBox(self.splitter_32)
        self.gen_sweep_step_vd.setDecimals(3)
        self.gen_sweep_step_vd.setMinimum(-99.0)
        self.gen_sweep_step_vd.setSingleStep(0.1)
        self.gen_sweep_step_vd.setObjectName("gen_sweep_step_vd")
        self.GateTab_2.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.splitter_34 = QtWidgets.QSplitter(self.tab_14)
        self.splitter_34.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.splitter_34.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_34.setObjectName("splitter_34")
        self.label_37 = QtWidgets.QLabel(self.splitter_34)
        self.label_37.setObjectName("label_37")
        self.gen_cyc_start_vd = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.gen_cyc_start_vd.setDecimals(3)
        self.gen_cyc_start_vd.setMinimum(-99.0)
        self.gen_cyc_start_vd.setMaximum(99.999)
        self.gen_cyc_start_vd.setSingleStep(0.1)
        self.gen_cyc_start_vd.setObjectName("gen_cyc_start_vd")
        self.label_38 = QtWidgets.QLabel(self.splitter_34)
        self.label_38.setObjectName("label_38")
        self.gen_cyc_max_vd = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.gen_cyc_max_vd.setDecimals(3)
        self.gen_cyc_max_vd.setMinimum(-99.999)
        self.gen_cyc_max_vd.setMaximum(99.999)
        self.gen_cyc_max_vd.setSingleStep(0.1)
        self.gen_cyc_max_vd.setObjectName("gen_cyc_max_vd")
        self.label_39 = QtWidgets.QLabel(self.splitter_34)
        self.label_39.setObjectName("label_39")
        self.gen_cyc_min_vd = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.gen_cyc_min_vd.setDecimals(3)
        self.gen_cyc_min_vd.setMinimum(-99.999)
        self.gen_cyc_min_vd.setMaximum(99.999)
        self.gen_cyc_min_vd.setSingleStep(0.1)
        self.gen_cyc_min_vd.setProperty("value", -0.8)
        self.gen_cyc_min_vd.setObjectName("gen_cyc_min_vd")
        self.label_40 = QtWidgets.QLabel(self.splitter_34)
        self.label_40.setObjectName("label_40")
        self.gen_cyc_step_vd = QtWidgets.QDoubleSpinBox(self.splitter_34)
        self.gen_cyc_step_vd.setDecimals(3)
        self.gen_cyc_step_vd.setMinimum(-99.999)
        self.gen_cyc_step_vd.setMaximum(99.999)
        self.gen_cyc_step_vd.setSingleStep(0.1)
        self.gen_cyc_step_vd.setProperty("value", 0.05)
        self.gen_cyc_step_vd.setObjectName("gen_cyc_step_vd")
        self.label_41 = QtWidgets.QLabel(self.splitter_34)
        self.label_41.setObjectName("label_41")
        self.gen_cycnum_vd = QtWidgets.QSpinBox(self.splitter_34)
        self.gen_cycnum_vd.setProperty("value", 3)
        self.gen_cycnum_vd.setObjectName("gen_cycnum_vd")
        self.GateTab_2.addTab(self.tab_14, "")
        self.Output.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.splitter_13 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_13.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.Start_resistance = QtWidgets.QPushButton(self.splitter_13)
        self.Start_resistance.setObjectName("Start_resistance")
        self.Stop_resistance = QtWidgets.QPushButton(self.splitter_13)
        self.Stop_resistance.setObjectName("Stop_resistance")
        self.splitter_10 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_10.setGeometry(QtCore.QRect(0, 20, 541, 231))
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName("splitter_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_10)
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter_12 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_12.setGeometry(QtCore.QRect(10, 30, 456, 20))
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.label_3 = QtWidgets.QLabel(self.splitter_12)
        self.label_3.setObjectName("label_3")
        self.spinbox_res_Vdstart = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdstart.setDecimals(3)
        self.spinbox_res_Vdstart.setMinimum(-99.999)
        self.spinbox_res_Vdstart.setMaximum(99.999)
        self.spinbox_res_Vdstart.setSingleStep(0.1)
        self.spinbox_res_Vdstart.setProperty("value", 0.0)
        self.spinbox_res_Vdstart.setObjectName("spinbox_res_Vdstart")
        self.label_43 = QtWidgets.QLabel(self.splitter_12)
        self.label_43.setObjectName("label_43")
        self.spinbox_res_Vdmax = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdmax.setDecimals(3)
        self.spinbox_res_Vdmax.setMinimum(-99.999)
        self.spinbox_res_Vdmax.setMaximum(99.999)
        self.spinbox_res_Vdmax.setSingleStep(0.1)
        self.spinbox_res_Vdmax.setProperty("value", 0.2)
        self.spinbox_res_Vdmax.setObjectName("spinbox_res_Vdmax")
        self.label_4 = QtWidgets.QLabel(self.splitter_12)
        self.label_4.setObjectName("label_4")
        self.spinbox_res_Vdmin = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdmin.setDecimals(3)
        self.spinbox_res_Vdmin.setMinimum(-99.999)
        self.spinbox_res_Vdmin.setMaximum(99.999)
        self.spinbox_res_Vdmin.setSingleStep(0.1)
        self.spinbox_res_Vdmin.setProperty("value", -0.2)
        self.spinbox_res_Vdmin.setObjectName("spinbox_res_Vdmin")
        self.label_5 = QtWidgets.QLabel(self.splitter_12)
        self.label_5.setObjectName("label_5")
        self.spinbox_res_Vdstep = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.spinbox_res_Vdstep.setDecimals(3)
        self.spinbox_res_Vdstep.setMinimum(-99.999)
        self.spinbox_res_Vdstep.setMaximum(99.999)
        self.spinbox_res_Vdstep.setSingleStep(0.01)
        self.spinbox_res_Vdstep.setProperty("value", 0.05)
        self.spinbox_res_Vdstep.setObjectName("spinbox_res_Vdstep")
        self.label_6 = QtWidgets.QLabel(self.splitter_12)
        self.label_6.setObjectName("label_6")
        self.spinbox_res_cycles = QtWidgets.QSpinBox(self.splitter_12)
        self.spinbox_res_cycles.setProperty("value", 2)
        self.spinbox_res_cycles.setObjectName("spinbox_res_cycles")
        self.Output.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.splitter_14 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_14.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.Start_transfer = QtWidgets.QPushButton(self.splitter_14)
        self.Start_transfer.setObjectName("Start_transfer")
        self.Stop_transfer = QtWidgets.QPushButton(self.splitter_14)
        self.Stop_transfer.setObjectName("Stop_transfer")
        self.splitter_17 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_17.setGeometry(QtCore.QRect(0, 20, 541, 221))
        self.splitter_17.setOrientation(QtCore.Qt.Vertical)
        self.splitter_17.setObjectName("splitter_17")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_17)
        self.groupBox_4.setObjectName("groupBox_4")
        self.splitter_19 = QtWidgets.QSplitter(self.groupBox_4)
        self.splitter_19.setGeometry(QtCore.QRect(10, 30, 521, 31))
        self.splitter_19.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_19.setObjectName("splitter_19")
        self.label_7 = QtWidgets.QLabel(self.splitter_19)
        self.label_7.setObjectName("label_7")
        self.Spinbox_Transfer_Vgstart = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgstart.setDecimals(3)
        self.Spinbox_Transfer_Vgstart.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgstart.setMaximum(99.999)
        self.Spinbox_Transfer_Vgstart.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgstart.setObjectName("Spinbox_Transfer_Vgstart")
        self.label_8 = QtWidgets.QLabel(self.splitter_19)
        self.label_8.setObjectName("label_8")
        self.Spinbox_Transfer_Vgmax = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgmax.setDecimals(3)
        self.Spinbox_Transfer_Vgmax.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgmax.setMaximum(99.999)
        self.Spinbox_Transfer_Vgmax.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgmax.setProperty("value", 0.8)
        self.Spinbox_Transfer_Vgmax.setObjectName("Spinbox_Transfer_Vgmax")
        self.label_10 = QtWidgets.QLabel(self.splitter_19)
        self.label_10.setObjectName("label_10")
        self.Spinbox_Transfer_Vgmin = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgmin.setDecimals(3)
        self.Spinbox_Transfer_Vgmin.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgmin.setMaximum(99.999)
        self.Spinbox_Transfer_Vgmin.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgmin.setProperty("value", -0.8)
        self.Spinbox_Transfer_Vgmin.setObjectName("Spinbox_Transfer_Vgmin")
        self.label_9 = QtWidgets.QLabel(self.splitter_19)
        self.label_9.setObjectName("label_9")
        self.Spinbox_Transfer_Vgstep = QtWidgets.QDoubleSpinBox(self.splitter_19)
        self.Spinbox_Transfer_Vgstep.setDecimals(3)
        self.Spinbox_Transfer_Vgstep.setMinimum(-99.999)
        self.Spinbox_Transfer_Vgstep.setSingleStep(0.1)
        self.Spinbox_Transfer_Vgstep.setProperty("value", -0.05)
        self.Spinbox_Transfer_Vgstep.setObjectName("Spinbox_Transfer_Vgstep")
        self.label_11 = QtWidgets.QLabel(self.splitter_19)
        self.label_11.setObjectName("label_11")
        self.Spinbox_Transfer_cycles = QtWidgets.QSpinBox(self.splitter_19)
        self.Spinbox_Transfer_cycles.setProperty("value", 3)
        self.Spinbox_Transfer_cycles.setObjectName("Spinbox_Transfer_cycles")
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter_17)
        self.groupBox_5.setObjectName("groupBox_5")
        self.splitter_20 = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter_20.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.splitter_20.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_20.setObjectName("splitter_20")
        self.label_12 = QtWidgets.QLabel(self.splitter_20)
        self.label_12.setObjectName("label_12")
        self.Spinbox_Transfer_Vd = QtWidgets.QDoubleSpinBox(self.splitter_20)
        self.Spinbox_Transfer_Vd.setDecimals(3)
        self.Spinbox_Transfer_Vd.setMinimum(-99.999)
        self.Spinbox_Transfer_Vd.setMaximum(99.999)
        self.Spinbox_Transfer_Vd.setSingleStep(0.1)
        self.Spinbox_Transfer_Vd.setProperty("value", -0.2)
        self.Spinbox_Transfer_Vd.setObjectName("Spinbox_Transfer_Vd")
        self.Output.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 30, 541, 108))
        self.groupBox_11.setObjectName("groupBox_11")
        self.splitter_45 = QtWidgets.QSplitter(self.groupBox_11)
        self.splitter_45.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.splitter_45.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_45.setObjectName("splitter_45")
        self.label_76 = QtWidgets.QLabel(self.splitter_45)
        self.label_76.setObjectName("label_76")
        self.Spinbox_output_Vg = QtWidgets.QDoubleSpinBox(self.splitter_45)
        self.Spinbox_output_Vg.setDecimals(3)
        self.Spinbox_output_Vg.setMinimum(-99.999)
        self.Spinbox_output_Vg.setMaximum(99.999)
        self.Spinbox_output_Vg.setSingleStep(0.1)
        self.Spinbox_output_Vg.setProperty("value", 0.0)
        self.Spinbox_output_Vg.setObjectName("Spinbox_output_Vg")
        self.DrainVbox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.DrainVbox_2.setGeometry(QtCore.QRect(10, 140, 531, 113))
        self.DrainVbox_2.setObjectName("DrainVbox_2")
        self.Vd_tab = QtWidgets.QTabWidget(self.DrainVbox_2)
        self.Vd_tab.setGeometry(QtCore.QRect(0, 20, 531, 91))
        self.Vd_tab.setTabBarAutoHide(False)
        self.Vd_tab.setObjectName("Vd_tab")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.splitter_46 = QtWidgets.QSplitter(self.tab_16)
        self.splitter_46.setGeometry(QtCore.QRect(20, 20, 421, 20))
        self.splitter_46.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_46.setObjectName("splitter_46")
        self.label_73 = QtWidgets.QLabel(self.splitter_46)
        self.label_73.setObjectName("label_73")
        self.output_sweep_start_vd = QtWidgets.QDoubleSpinBox(self.splitter_46)
        self.output_sweep_start_vd.setDecimals(3)
        self.output_sweep_start_vd.setMinimum(-99.0)
        self.output_sweep_start_vd.setSingleStep(0.1)
        self.output_sweep_start_vd.setObjectName("output_sweep_start_vd")
        self.label_74 = QtWidgets.QLabel(self.splitter_46)
        self.label_74.setObjectName("label_74")
        self.output_sweep_stop_vd = QtWidgets.QDoubleSpinBox(self.splitter_46)
        self.output_sweep_stop_vd.setDecimals(3)
        self.output_sweep_stop_vd.setMinimum(-99.0)
        self.output_sweep_stop_vd.setSingleStep(0.1)
        self.output_sweep_stop_vd.setProperty("value", -0.8)
        self.output_sweep_stop_vd.setObjectName("output_sweep_stop_vd")
        self.label_75 = QtWidgets.QLabel(self.splitter_46)
        self.label_75.setObjectName("label_75")
        self.output_sweep_step_vd = QtWidgets.QDoubleSpinBox(self.splitter_46)
        self.output_sweep_step_vd.setDecimals(3)
        self.output_sweep_step_vd.setMinimum(-99.0)
        self.output_sweep_step_vd.setSingleStep(0.1)
        self.output_sweep_step_vd.setProperty("value", 0.05)
        self.output_sweep_step_vd.setObjectName("output_sweep_step_vd")
        self.Vd_tab.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.splitter_47 = QtWidgets.QSplitter(self.tab_17)
        self.splitter_47.setGeometry(QtCore.QRect(10, 10, 511, 31))
        self.splitter_47.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_47.setObjectName("splitter_47")
        self.label_77 = QtWidgets.QLabel(self.splitter_47)
        self.label_77.setObjectName("label_77")
        self.output_cyc_start_vd = QtWidgets.QDoubleSpinBox(self.splitter_47)
        self.output_cyc_start_vd.setDecimals(3)
        self.output_cyc_start_vd.setMinimum(-99.0)
        self.output_cyc_start_vd.setMaximum(99.999)
        self.output_cyc_start_vd.setSingleStep(0.1)
        self.output_cyc_start_vd.setObjectName("output_cyc_start_vd")
        self.label_78 = QtWidgets.QLabel(self.splitter_47)
        self.label_78.setObjectName("label_78")
        self.output_cyc_max_vd = QtWidgets.QDoubleSpinBox(self.splitter_47)
        self.output_cyc_max_vd.setDecimals(3)
        self.output_cyc_max_vd.setMinimum(-99.999)
        self.output_cyc_max_vd.setMaximum(99.999)
        self.output_cyc_max_vd.setSingleStep(0.1)
        self.output_cyc_max_vd.setObjectName("output_cyc_max_vd")
        self.label_79 = QtWidgets.QLabel(self.splitter_47)
        self.label_79.setObjectName("label_79")
        self.output_cyc_min_vd = QtWidgets.QDoubleSpinBox(self.splitter_47)
        self.output_cyc_min_vd.setDecimals(3)
        self.output_cyc_min_vd.setMinimum(-99.999)
        self.output_cyc_min_vd.setMaximum(99.999)
        self.output_cyc_min_vd.setSingleStep(0.1)
        self.output_cyc_min_vd.setProperty("value", -0.8)
        self.output_cyc_min_vd.setObjectName("output_cyc_min_vd")
        self.label_80 = QtWidgets.QLabel(self.splitter_47)
        self.label_80.setObjectName("label_80")
        self.output_cyc_step_vd = QtWidgets.QDoubleSpinBox(self.splitter_47)
        self.output_cyc_step_vd.setDecimals(3)
        self.output_cyc_step_vd.setMinimum(-99.999)
        self.output_cyc_step_vd.setMaximum(99.999)
        self.output_cyc_step_vd.setSingleStep(0.1)
        self.output_cyc_step_vd.setProperty("value", 0.05)
        self.output_cyc_step_vd.setObjectName("output_cyc_step_vd")
        self.label_81 = QtWidgets.QLabel(self.splitter_47)
        self.label_81.setObjectName("label_81")
        self.output_cycnum_vd = QtWidgets.QSpinBox(self.splitter_47)
        self.output_cycnum_vd.setProperty("value", 3)
        self.output_cycnum_vd.setObjectName("output_cycnum_vd")
        self.Vd_tab.addTab(self.tab_17, "")
        self.Stop_output = QtWidgets.QPushButton(self.tab_4)
        self.Stop_output.setGeometry(QtCore.QRect(120, 260, 93, 51))
        self.Stop_output.setObjectName("Stop_output")
        self.Start_output = QtWidgets.QPushButton(self.tab_4)
        self.Start_output.setGeometry(QtCore.QRect(22, 260, 93, 51))
        self.Start_output.setObjectName("Start_output")
        self.Output.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 140, 581, 151))
        self.groupBox_8.setObjectName("groupBox_8")
        self.proteinBSAtab = QtWidgets.QTabWidget(self.groupBox_8)
        self.proteinBSAtab.setGeometry(QtCore.QRect(10, 20, 561, 131))
        self.proteinBSAtab.setObjectName("proteinBSAtab")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.splitter_24 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_24.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.splitter_24.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_24.setObjectName("splitter_24")
        self.label_16 = QtWidgets.QLabel(self.splitter_24)
        self.label_16.setObjectName("label_16")
        self.timeBSA = QtWidgets.QTimeEdit(self.splitter_24)
        self.timeBSA.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeBSA.setTime(QtCore.QTime(0, 5, 0))
        self.timeBSA.setObjectName("timeBSA")
        self.splitter_25 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_25.setGeometry(QtCore.QRect(10, 60, 221, 31))
        self.splitter_25.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_25.setObjectName("splitter_25")
        self.label_17 = QtWidgets.QLabel(self.splitter_25)
        self.label_17.setObjectName("label_17")
        self.radioButton = QtWidgets.QRadioButton(self.splitter_25)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter_25)
        self.radioButton_2.setObjectName("radioButton_2")
        self.splitter_38 = QtWidgets.QSplitter(self.tab_10)
        self.splitter_38.setGeometry(QtCore.QRect(10, 40, 201, 17))
        self.splitter_38.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_38.setObjectName("splitter_38")
        self.label_63 = QtWidgets.QLabel(self.splitter_38)
        self.label_63.setObjectName("label_63")
        self.check_BSAtime = QtWidgets.QCheckBox(self.splitter_38)
        self.check_BSAtime.setTristate(False)
        self.check_BSAtime.setObjectName("check_BSAtime")
        self.label_21 = QtWidgets.QLabel(self.tab_10)
        self.label_21.setGeometry(QtCore.QRect(260, 10, 83, 16))
        self.label_21.setObjectName("label_21")
        self.combo_BSA = QtWidgets.QComboBox(self.tab_10)
        self.combo_BSA.setGeometry(QtCore.QRect(260, 30, 81, 31))
        self.combo_BSA.setObjectName("combo_BSA")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.combo_BSA.addItem("")
        self.proteinBSAtab.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.splitter_26 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_26.setGeometry(QtCore.QRect(10, 60, 221, 31))
        self.splitter_26.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_26.setObjectName("splitter_26")
        self.label_18 = QtWidgets.QLabel(self.splitter_26)
        self.label_18.setObjectName("label_18")
        self.radioButton_limit_Id = QtWidgets.QRadioButton(self.splitter_26)
        self.radioButton_limit_Id.setObjectName("radioButton_limit_Id")
        self.radioButton_no_limit = QtWidgets.QRadioButton(self.splitter_26)
        self.radioButton_no_limit.setObjectName("radioButton_no_limit")
        self.splitter_27 = QtWidgets.QSplitter(self.tab_11)
        self.splitter_27.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.splitter_27.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_27.setObjectName("splitter_27")
        self.label_19 = QtWidgets.QLabel(self.splitter_27)
        self.label_19.setObjectName("label_19")
        self.timeProtein = QtWidgets.QTimeEdit(self.splitter_27)
        self.timeProtein.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeProtein.setTime(QtCore.QTime(0, 2, 0))
        self.timeProtein.setObjectName("timeProtein")
        self.check_proteintime = QtWidgets.QCheckBox(self.tab_11)
        self.check_proteintime.setGeometry(QtCore.QRect(162, 40, 49, 17))
        self.check_proteintime.setObjectName("check_proteintime")
        self.label_64 = QtWidgets.QLabel(self.tab_11)
        self.label_64.setGeometry(QtCore.QRect(10, 40, 147, 17))
        self.label_64.setObjectName("label_64")
        self.label_20 = QtWidgets.QLabel(self.tab_11)
        self.label_20.setGeometry(QtCore.QRect(260, 10, 115, 16))
        self.label_20.setObjectName("label_20")
        self.combo_protein = QtWidgets.QComboBox(self.tab_11)
        self.combo_protein.setGeometry(QtCore.QRect(260, 30, 91, 31))
        self.combo_protein.setObjectName("combo_protein")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.combo_protein.addItem("")
        self.proteinBSAtab.addTab(self.tab_11, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.splitter_41 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_41.setGeometry(QtCore.QRect(10, 60, 221, 31))
        self.splitter_41.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_41.setObjectName("splitter_41")
        self.label_67 = QtWidgets.QLabel(self.splitter_41)
        self.label_67.setObjectName("label_67")
        self.radioButton_limit_Id_2 = QtWidgets.QRadioButton(self.splitter_41)
        self.radioButton_limit_Id_2.setObjectName("radioButton_limit_Id_2")
        self.radioButton_no_limit_2 = QtWidgets.QRadioButton(self.splitter_41)
        self.radioButton_no_limit_2.setObjectName("radioButton_no_limit_2")
        self.label_68 = QtWidgets.QLabel(self.tab_3)
        self.label_68.setGeometry(QtCore.QRect(260, 0, 134, 31))
        self.label_68.setObjectName("label_68")
        self.text_ions = QtWidgets.QTextEdit(self.tab_3)
        self.text_ions.setGeometry(QtCore.QRect(250, 30, 211, 71))
        self.text_ions.setObjectName("text_ions")
        self.splitter_39 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_39.setGeometry(QtCore.QRect(10, 10, 221, 20))
        self.splitter_39.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_39.setObjectName("splitter_39")
        self.label_65 = QtWidgets.QLabel(self.splitter_39)
        self.label_65.setObjectName("label_65")
        self.timeIon = QtWidgets.QTimeEdit(self.splitter_39)
        self.timeIon.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.timeIon.setTime(QtCore.QTime(0, 5, 0))
        self.timeIon.setObjectName("timeIon")
        self.splitter_40 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_40.setGeometry(QtCore.QRect(10, 40, 201, 17))
        self.splitter_40.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_40.setObjectName("splitter_40")
        self.label_66 = QtWidgets.QLabel(self.splitter_40)
        self.label_66.setObjectName("label_66")
        self.check_iontime = QtWidgets.QCheckBox(self.splitter_40)
        self.check_iontime.setObjectName("check_iontime")
        self.proteinBSAtab.addTab(self.tab_3, "")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 291, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.splitter_21 = QtWidgets.QSplitter(self.groupBox_6)
        self.splitter_21.setGeometry(QtCore.QRect(90, 20, 141, 31))
        self.splitter_21.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_21.setObjectName("splitter_21")
        self.label_13 = QtWidgets.QLabel(self.splitter_21)
        self.label_13.setObjectName("label_13")
        self.spinbox_vg = QtWidgets.QDoubleSpinBox(self.splitter_21)
        self.spinbox_vg.setWrapping(False)
        self.spinbox_vg.setDecimals(3)
        self.spinbox_vg.setMinimum(-99.999)
        self.spinbox_vg.setMaximum(99.999)
        self.spinbox_vg.setSingleStep(0.1)
        self.spinbox_vg.setProperty("value", -0.5)
        self.spinbox_vg.setObjectName("spinbox_vg")
        self.splitter_42 = QtWidgets.QSplitter(self.groupBox_6)
        self.splitter_42.setGeometry(QtCore.QRect(10, 60, 171, 41))
        self.splitter_42.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_42.setObjectName("splitter_42")
        self.label_69 = QtWidgets.QLabel(self.splitter_42)
        self.label_69.setObjectName("label_69")
        self.check_vg_turnoff = QtWidgets.QCheckBox(self.splitter_42)
        self.check_vg_turnoff.setObjectName("check_vg_turnoff")
        self.radio_gate_DC = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_gate_DC.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.radio_gate_DC.setObjectName("radio_gate_DC")
        self.radio_gate_AC = QtWidgets.QRadioButton(self.groupBox_6)
        self.radio_gate_AC.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.radio_gate_AC.setObjectName("radio_gate_AC")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_7.setGeometry(QtCore.QRect(290, 10, 291, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.splitter_22 = QtWidgets.QSplitter(self.groupBox_7)
        self.splitter_22.setGeometry(QtCore.QRect(10, 20, 141, 31))
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setObjectName("splitter_22")
        self.label_14 = QtWidgets.QLabel(self.splitter_22)
        self.label_14.setObjectName("label_14")
        self.spinbox_vd = QtWidgets.QDoubleSpinBox(self.splitter_22)
        self.spinbox_vd.setProperty("showGroupSeparator", False)
        self.spinbox_vd.setDecimals(3)
        self.spinbox_vd.setMinimum(-99.999)
        self.spinbox_vd.setSingleStep(0.1)
        self.spinbox_vd.setProperty("value", -0.5)
        self.spinbox_vd.setObjectName("spinbox_vd")
        self.splitter_43 = QtWidgets.QSplitter(self.groupBox_7)
        self.splitter_43.setGeometry(QtCore.QRect(10, 60, 171, 41))
        self.splitter_43.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_43.setObjectName("splitter_43")
        self.label_70 = QtWidgets.QLabel(self.splitter_43)
        self.label_70.setObjectName("label_70")
        self.check_vd_turnoff = QtWidgets.QCheckBox(self.splitter_43)
        self.check_vd_turnoff.setObjectName("check_vd_turnoff")
        self.Update_online = QtWidgets.QPushButton(self.tab_6)
        self.Update_online.setGeometry(QtCore.QRect(400, 300, 92, 51))
        self.Update_online.setObjectName("Update_online")
        self.splitter_18 = QtWidgets.QSplitter(self.tab_6)
        self.splitter_18.setGeometry(QtCore.QRect(10, 300, 381, 51))
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.splitter_15 = QtWidgets.QSplitter(self.splitter_18)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.Start_online = QtWidgets.QPushButton(self.splitter_15)
        self.Start_online.setObjectName("Start_online")
        self.Stop_online = QtWidgets.QPushButton(self.splitter_15)
        self.Stop_online.setObjectName("Stop_online")
        self.Pause_online = QtWidgets.QPushButton(self.splitter_18)
        self.Pause_online.setObjectName("Pause_online")
        self.Continue_online = QtWidgets.QPushButton(self.splitter_18)
        self.Continue_online.setObjectName("Continue_online")
        self.Output.addTab(self.tab_6, "")
        self.impedance = QtWidgets.QWidget()
        self.impedance.setObjectName("impedance")
        self.splitter_23 = QtWidgets.QSplitter(self.impedance)
        self.splitter_23.setGeometry(QtCore.QRect(20, 260, 191, 51))
        self.splitter_23.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_23.setObjectName("splitter_23")
        self.Start_impedance = QtWidgets.QPushButton(self.splitter_23)
        self.Start_impedance.setObjectName("Start_impedance")
        self.Stop_impedance = QtWidgets.QPushButton(self.splitter_23)
        self.Stop_impedance.setObjectName("Stop_impedance")
        self.label_15 = QtWidgets.QLabel(self.impedance)
        self.label_15.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.label_15.setObjectName("label_15")
        self.doubleSpin_oscamp = QtWidgets.QDoubleSpinBox(self.impedance)
        self.doubleSpin_oscamp.setGeometry(QtCore.QRect(120, 50, 71, 22))
        self.doubleSpin_oscamp.setDecimals(3)
        self.doubleSpin_oscamp.setSingleStep(0.01)
        self.doubleSpin_oscamp.setObjectName("doubleSpin_oscamp")
        self.label_44 = QtWidgets.QLabel(self.impedance)
        self.label_44.setGeometry(QtCore.QRect(200, 50, 41, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.impedance)
        self.label_45.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.impedance)
        self.label_46.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.impedance)
        self.label_47.setGeometry(QtCore.QRect(10, 150, 121, 21))
        self.label_47.setObjectName("label_47")
        self.doubleSpin_startf = QtWidgets.QDoubleSpinBox(self.impedance)
        self.doubleSpin_startf.setGeometry(QtCore.QRect(120, 90, 101, 22))
        self.doubleSpin_startf.setDecimals(3)
        self.doubleSpin_startf.setMaximum(250000.0)
        self.doubleSpin_startf.setSingleStep(0.01)
        self.doubleSpin_startf.setProperty("value", 1.0)
        self.doubleSpin_startf.setObjectName("doubleSpin_startf")
        self.label_48 = QtWidgets.QLabel(self.impedance)
        self.label_48.setGeometry(QtCore.QRect(240, 90, 41, 21))
        self.label_48.setObjectName("label_48")
        self.doubleSpin_stopf = QtWidgets.QDoubleSpinBox(self.impedance)
        self.doubleSpin_stopf.setGeometry(QtCore.QRect(120, 120, 101, 22))
        self.doubleSpin_stopf.setDecimals(3)
        self.doubleSpin_stopf.setMaximum(250000.0)
        self.doubleSpin_stopf.setSingleStep(0.01)
        self.doubleSpin_stopf.setProperty("value", 250000.0)
        self.doubleSpin_stopf.setObjectName("doubleSpin_stopf")
        self.label_49 = QtWidgets.QLabel(self.impedance)
        self.label_49.setGeometry(QtCore.QRect(240, 120, 41, 21))
        self.label_49.setObjectName("label_49")
        self.spinBox_num = QtWidgets.QSpinBox(self.impedance)
        self.spinBox_num.setGeometry(QtCore.QRect(121, 150, 61, 22))
        self.spinBox_num.setMinimum(2)
        self.spinBox_num.setMaximum(10000)
        self.spinBox_num.setProperty("value", 100)
        self.spinBox_num.setObjectName("spinBox_num")
        self.splitter_37 = QtWidgets.QSplitter(self.impedance)
        self.splitter_37.setGeometry(QtCore.QRect(290, 120, 161, 51))
        self.splitter_37.setOrientation(QtCore.Qt.Vertical)
        self.splitter_37.setObjectName("splitter_37")
        self.label_51 = QtWidgets.QLabel(self.splitter_37)
        self.label_51.setObjectName("label_51")
        self.text_solution = QtWidgets.QTextEdit(self.splitter_37)
        self.text_solution.setObjectName("text_solution")
        self.splitter_5 = QtWidgets.QSplitter(self.impedance)
        self.splitter_5.setGeometry(QtCore.QRect(290, 50, 161, 51))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.label_50 = QtWidgets.QLabel(self.splitter_5)
        self.label_50.setObjectName("label_50")
        self.text_electrodes = QtWidgets.QTextEdit(self.splitter_5)
        self.text_electrodes.setObjectName("text_electrodes")
        self.radioButton_FET = QtWidgets.QRadioButton(self.impedance)
        self.radioButton_FET.setGeometry(QtCore.QRect(120, 190, 81, 16))
        self.radioButton_FET.setObjectName("radioButton_FET")
        self.radioButton_BJT = QtWidgets.QRadioButton(self.impedance)
        self.radioButton_BJT.setGeometry(QtCore.QRect(120, 210, 81, 16))
        self.radioButton_BJT.setObjectName("radioButton_BJT")
        self.label_59 = QtWidgets.QLabel(self.impedance)
        self.label_59.setGeometry(QtCore.QRect(10, 190, 81, 21))
        self.label_59.setObjectName("label_59")
        self.Output.addTab(self.impedance, "")
        self.cv_tab = QtWidgets.QWidget()
        self.cv_tab.setObjectName("cv_tab")
        self.start_voltammetry = QtWidgets.QPushButton(self.cv_tab)
        self.start_voltammetry.setGeometry(QtCore.QRect(320, 370, 75, 23))
        self.start_voltammetry.setObjectName("start_voltammetry")
        self.stop_voltammetry = QtWidgets.QPushButton(self.cv_tab)
        self.stop_voltammetry.setGeometry(QtCore.QRect(420, 370, 75, 23))
        self.stop_voltammetry.setObjectName("stop_voltammetry")
        self.label_52 = QtWidgets.QLabel(self.cv_tab)
        self.label_52.setGeometry(QtCore.QRect(120, 60, 51, 31))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.cv_tab)
        self.label_53.setGeometry(QtCore.QRect(120, 90, 51, 31))
        self.label_53.setObjectName("label_53")
        self.doubleSpinBox_startV = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.doubleSpinBox_startV.setGeometry(QtCore.QRect(30, 60, 62, 22))
        self.doubleSpinBox_startV.setMinimum(-2.0)
        self.doubleSpinBox_startV.setMaximum(2.0)
        self.doubleSpinBox_startV.setSingleStep(0.1)
        self.doubleSpinBox_startV.setObjectName("doubleSpinBox_startV")
        self.doubleSpinBox_endV = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.doubleSpinBox_endV.setGeometry(QtCore.QRect(30, 90, 62, 22))
        self.doubleSpinBox_endV.setMinimum(-2.0)
        self.doubleSpinBox_endV.setMaximum(2.0)
        self.doubleSpinBox_endV.setSingleStep(0.1)
        self.doubleSpinBox_endV.setProperty("value", 0.8)
        self.doubleSpinBox_endV.setObjectName("doubleSpinBox_endV")
        self.doubleSpinBox_scan_rate = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.doubleSpinBox_scan_rate.setGeometry(QtCore.QRect(30, 150, 62, 22))
        self.doubleSpinBox_scan_rate.setMaximum(10000.0)
        self.doubleSpinBox_scan_rate.setProperty("value", 100.0)
        self.doubleSpinBox_scan_rate.setObjectName("doubleSpinBox_scan_rate")
        self.spinBox_cycles = QtWidgets.QSpinBox(self.cv_tab)
        self.spinBox_cycles.setGeometry(QtCore.QRect(30, 210, 42, 22))
        self.spinBox_cycles.setMaximum(5000)
        self.spinBox_cycles.setProperty("value", 3)
        self.spinBox_cycles.setObjectName("spinBox_cycles")
        self.label_54 = QtWidgets.QLabel(self.cv_tab)
        self.label_54.setGeometry(QtCore.QRect(120, 150, 91, 31))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.cv_tab)
        self.label_55.setGeometry(QtCore.QRect(80, 200, 51, 31))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.cv_tab)
        self.label_56.setGeometry(QtCore.QRect(120, 180, 71, 31))
        self.label_56.setObjectName("label_56")
        self.doubleSpinBox_step_size = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.doubleSpinBox_step_size.setGeometry(QtCore.QRect(30, 180, 62, 22))
        self.doubleSpinBox_step_size.setMaximum(1000.0)
        self.doubleSpinBox_step_size.setProperty("value", 50.0)
        self.doubleSpinBox_step_size.setObjectName("doubleSpinBox_step_size")
        self.spinbox_I_limit = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.spinbox_I_limit.setGeometry(QtCore.QRect(30, 240, 76, 31))
        self.spinbox_I_limit.setDecimals(3)
        self.spinbox_I_limit.setMaximum(1000.0)
        self.spinbox_I_limit.setSingleStep(1.0)
        self.spinbox_I_limit.setProperty("value", 100.0)
        self.spinbox_I_limit.setObjectName("spinbox_I_limit")
        self.label_57 = QtWidgets.QLabel(self.cv_tab)
        self.label_57.setGeometry(QtCore.QRect(120, 240, 101, 31))
        self.label_57.setObjectName("label_57")
        self.doubleSpinBox_minV = QtWidgets.QDoubleSpinBox(self.cv_tab)
        self.doubleSpinBox_minV.setGeometry(QtCore.QRect(30, 120, 62, 22))
        self.doubleSpinBox_minV.setMinimum(-2.0)
        self.doubleSpinBox_minV.setMaximum(2.0)
        self.doubleSpinBox_minV.setSingleStep(0.1)
        self.doubleSpinBox_minV.setProperty("value", -0.8)
        self.doubleSpinBox_minV.setObjectName("doubleSpinBox_minV")
        self.label_58 = QtWidgets.QLabel(self.cv_tab)
        self.label_58.setGeometry(QtCore.QRect(120, 120, 51, 31))
        self.label_58.setObjectName("label_58")
        self.Output.addTab(self.cv_tab, "")
        self.Potentiostat = QtWidgets.QWidget()
        self.Potentiostat.setObjectName("Potentiostat")
        self.start_potentialMeas = QtWidgets.QPushButton(self.Potentiostat)
        self.start_potentialMeas.setGeometry(QtCore.QRect(170, 130, 75, 23))
        self.start_potentialMeas.setObjectName("start_potentialMeas")
        self.stop_potentialMeas = QtWidgets.QPushButton(self.Potentiostat)
        self.stop_potentialMeas.setGeometry(QtCore.QRect(270, 130, 75, 23))
        self.stop_potentialMeas.setObjectName("stop_potentialMeas")
        self.doubleSpinBox_measurementDuration = QtWidgets.QDoubleSpinBox(self.Potentiostat)
        self.doubleSpinBox_measurementDuration.setGeometry(QtCore.QRect(170, 90, 62, 22))
        self.doubleSpinBox_measurementDuration.setMaximum(10000.0)
        self.doubleSpinBox_measurementDuration.setProperty("value", 100.0)
        self.doubleSpinBox_measurementDuration.setObjectName("doubleSpinBox_measurementDuration")
        self.doubleSpinBox_measDelay = QtWidgets.QDoubleSpinBox(self.Potentiostat)
        self.doubleSpinBox_measDelay.setGeometry(QtCore.QRect(170, 50, 62, 22))
        self.doubleSpinBox_measDelay.setMaximum(10000.0)
        self.doubleSpinBox_measDelay.setProperty("value", 100.0)
        self.doubleSpinBox_measDelay.setObjectName("doubleSpinBox_measDelay")
        self.label_60 = QtWidgets.QLabel(self.Potentiostat)
        self.label_60.setGeometry(QtCore.QRect(40, 90, 131, 21))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.Potentiostat)
        self.label_61.setGeometry(QtCore.QRect(40, 50, 131, 21))
        self.label_61.setObjectName("label_61")
        self.comboBox_potentiostatChannel = QtWidgets.QComboBox(self.Potentiostat)
        self.comboBox_potentiostatChannel.setGeometry(QtCore.QRect(170, 20, 71, 22))
        self.comboBox_potentiostatChannel.setObjectName("comboBox_potentiostatChannel")
        self.comboBox_potentiostatChannel.addItem("")
        self.comboBox_potentiostatChannel.addItem("")
        self.label_62 = QtWidgets.QLabel(self.Potentiostat)
        self.label_62.setGeometry(QtCore.QRect(40, 20, 131, 21))
        self.label_62.setObjectName("label_62")
        self.Output.addTab(self.Potentiostat, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 461, 451))
        self.groupBox.setObjectName("groupBox")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(10, 200, 301, 91))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.CommentName = QtWidgets.QLabel(self.splitter_3)
        self.CommentName.setObjectName("CommentName")
        self.text_comments = QtWidgets.QTextEdit(self.splitter_3)
        self.text_comments.setObjectName("text_comments")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 300, 401, 61))
        self.groupBox_9.setObjectName("groupBox_9")
        self.splitter_30 = QtWidgets.QSplitter(self.groupBox_9)
        self.splitter_30.setGeometry(QtCore.QRect(10, 20, 381, 31))
        self.splitter_30.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_30.setObjectName("splitter_30")
        self.label_22 = QtWidgets.QLabel(self.splitter_30)
        self.label_22.setObjectName("label_22")
        self.spinbox_Ig_limit = QtWidgets.QDoubleSpinBox(self.splitter_30)
        self.spinbox_Ig_limit.setDecimals(3)
        self.spinbox_Ig_limit.setMaximum(1000.0)
        self.spinbox_Ig_limit.setSingleStep(1.0)
        self.spinbox_Ig_limit.setProperty("value", 1.0)
        self.spinbox_Ig_limit.setObjectName("spinbox_Ig_limit")
        self.label_23 = QtWidgets.QLabel(self.splitter_30)
        self.label_23.setObjectName("label_23")
        self.spinbox_Id_limit = QtWidgets.QDoubleSpinBox(self.splitter_30)
        self.spinbox_Id_limit.setDecimals(3)
        self.spinbox_Id_limit.setMaximum(1000.0)
        self.spinbox_Id_limit.setSingleStep(1.0)
        self.spinbox_Id_limit.setProperty("value", 1.0)
        self.spinbox_Id_limit.setObjectName("spinbox_Id_limit")
        self.splitter_6 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_6.setGeometry(QtCore.QRect(10, 100, 301, 91))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter = QtWidgets.QSplitter(self.splitter_6)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.SampleName = QtWidgets.QLabel(self.splitter)
        self.SampleName.setObjectName("SampleName")
        self.text_sample = QtWidgets.QTextEdit(self.splitter)
        self.text_sample.setObjectName("text_sample")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.DeviceName = QtWidgets.QLabel(self.splitter_2)
        self.DeviceName.setObjectName("DeviceName")
        self.text_device = QtWidgets.QTextEdit(self.splitter_2)
        self.text_device.setObjectName("text_device")
        self.splitter_36 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_36.setGeometry(QtCore.QRect(20, 370, 231, 31))
        self.splitter_36.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_36.setObjectName("splitter_36")
        self.label_42 = QtWidgets.QLabel(self.splitter_36)
        self.label_42.setObjectName("label_42")
        self.spinBox_DAQ = QtWidgets.QSpinBox(self.splitter_36)
        self.spinBox_DAQ.setMaximum(1000)
        self.spinBox_DAQ.setProperty("value", 250)
        self.spinBox_DAQ.setObjectName("spinBox_DAQ")
        self.text_filepath = QtWidgets.QTextBrowser(self.groupBox)
        self.text_filepath.setGeometry(QtCore.QRect(10, 54, 301, 31))
        self.text_filepath.setObjectName("text_filepath")
        self.splitter_4 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_4.setGeometry(QtCore.QRect(10, 30, 301, 19))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.FilePathName = QtWidgets.QLabel(self.splitter_4)
        self.FilePathName.setObjectName("FilePathName")
        self.defaultpath_button = QtWidgets.QToolButton(self.splitter_4)
        self.defaultpath_button.setObjectName("defaultpath_button")
        self.browseFile = QtWidgets.QToolButton(self.splitter_4)
        self.browseFile.setObjectName("browseFile")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 30, 121, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_mu_u2722a = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_mu_u2722a.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.radioButton_mu_u2722a.setAutoFillBackground(False)
        self.radioButton_mu_u2722a.setObjectName("radioButton_mu_u2722a")
        self.radioButton_mu_k2636 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_mu_k2636.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.radioButton_mu_k2636.setAutoFillBackground(False)
        self.radioButton_mu_k2636.setChecked(True)
        self.radioButton_mu_k2636.setObjectName("radioButton_mu_k2636")
        self.splitter_7 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_7.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_35 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_35.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_35.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_35.setObjectName("splitter_35")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Output.setCurrentIndex(4)
        self.GateTab.setCurrentIndex(1)
        self.GateTab_2.setCurrentIndex(1)
        self.Vd_tab.setCurrentIndex(0)
        self.proteinBSAtab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start_general.setText(_translate("MainWindow", "Start"))
        self.Stop_general.setText(_translate("MainWindow", "Stop"))
        self.GateVbox.setTitle(_translate("MainWindow", "Gate Voltage :"))
        self.label.setText(_translate("MainWindow", "Vg : "))
        self.label_2.setText(_translate("MainWindow", "[V]"))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_7), _translate("MainWindow", "Constant"))
        self.label_26.setText(_translate("MainWindow", "Start : "))
        self.label_27.setText(_translate("MainWindow", "Stop :"))
        self.label_28.setText(_translate("MainWindow", "Step :"))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_8), _translate("MainWindow", "Sweep"))
        self.label_32.setText(_translate("MainWindow", "Start : "))
        self.label_33.setText(_translate("MainWindow", "Max : "))
        self.label_34.setText(_translate("MainWindow", "Min :"))
        self.label_36.setText(_translate("MainWindow", "Step : "))
        self.label_35.setText(_translate("MainWindow", "Cycles : "))
        self.GateTab.setTabText(self.GateTab.indexOf(self.tab_9), _translate("MainWindow", "Cyclic"))
        self.DrainVbox.setTitle(_translate("MainWindow", "Drain Voltage : "))
        self.label_24.setText(_translate("MainWindow", "Vd : "))
        self.label_25.setText(_translate("MainWindow", "[V]"))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_12), _translate("MainWindow", "Constant"))
        self.label_29.setText(_translate("MainWindow", "Start : "))
        self.label_30.setText(_translate("MainWindow", "Stop :"))
        self.label_31.setText(_translate("MainWindow", "Step :"))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_13), _translate("MainWindow", "Sweep"))
        self.label_37.setText(_translate("MainWindow", "Start : "))
        self.label_38.setText(_translate("MainWindow", "Max : "))
        self.label_39.setText(_translate("MainWindow", "Min :"))
        self.label_40.setText(_translate("MainWindow", "Step : "))
        self.label_41.setText(_translate("MainWindow", "Cycles : "))
        self.GateTab_2.setTabText(self.GateTab_2.indexOf(self.tab_14), _translate("MainWindow", "Cyclic"))
        self.Output.setTabText(self.Output.indexOf(self.tab), _translate("MainWindow", "General"))
        self.Start_resistance.setText(_translate("MainWindow", "Start"))
        self.Stop_resistance.setText(_translate("MainWindow", "Stop"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drain Voltage [V]: "))
        self.label_3.setText(_translate("MainWindow", "Start : "))
        self.label_43.setText(_translate("MainWindow", "Max:"))
        self.label_4.setText(_translate("MainWindow", "Min: "))
        self.label_5.setText(_translate("MainWindow", "Step : "))
        self.label_6.setText(_translate("MainWindow", "Cycles:"))
        self.Output.setTabText(self.Output.indexOf(self.tab_5), _translate("MainWindow", "Resistance"))
        self.Start_transfer.setText(_translate("MainWindow", "Start"))
        self.Stop_transfer.setText(_translate("MainWindow", "Stop"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Gate Voltage [V] :"))
        self.label_7.setText(_translate("MainWindow", "Start :"))
        self.label_8.setText(_translate("MainWindow", "Max :"))
        self.label_10.setText(_translate("MainWindow", "Min : "))
        self.label_9.setText(_translate("MainWindow", "Step : "))
        self.label_11.setText(_translate("MainWindow", "Cycles :"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Drain Voltage [V] :"))
        self.label_12.setText(_translate("MainWindow", "Constant : "))
        self.Output.setTabText(self.Output.indexOf(self.tab_2), _translate("MainWindow", "Transfer"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Gate Voltage [V] :"))
        self.label_76.setText(_translate("MainWindow", "Constant : "))
        self.DrainVbox_2.setTitle(_translate("MainWindow", "Drain Voltage [V]: "))
        self.label_73.setText(_translate("MainWindow", "Start : "))
        self.label_74.setText(_translate("MainWindow", "Stop :"))
        self.label_75.setText(_translate("MainWindow", "Step :"))
        self.Vd_tab.setTabText(self.Vd_tab.indexOf(self.tab_16), _translate("MainWindow", "Sweep"))
        self.label_77.setText(_translate("MainWindow", "Start : "))
        self.label_78.setText(_translate("MainWindow", "Max : "))
        self.label_79.setText(_translate("MainWindow", "Min :"))
        self.label_80.setText(_translate("MainWindow", "Step : "))
        self.label_81.setText(_translate("MainWindow", "Cycles : "))
        self.Vd_tab.setTabText(self.Vd_tab.indexOf(self.tab_17), _translate("MainWindow", "Cyclic"))
        self.Stop_output.setText(_translate("MainWindow", "Stop"))
        self.Start_output.setText(_translate("MainWindow", "Start"))
        self.Output.setTabText(self.Output.indexOf(self.tab_4), _translate("MainWindow", "Output"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Measurement setup :"))
        self.label_16.setText(_translate("MainWindow", "Measurement Time [mm:ss] : "))
        self.timeBSA.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.label_17.setText(_translate("MainWindow", "Stop if Id < 2% :"))
        self.radioButton.setText(_translate("MainWindow", "Yes"))
        self.radioButton_2.setText(_translate("MainWindow", "No"))
        self.label_63.setText(_translate("MainWindow", "Unlimited measurement :"))
        self.check_BSAtime.setText(_translate("MainWindow", "Yes"))
        self.label_21.setText(_translate("MainWindow", "BSA application : "))
        self.combo_BSA.setItemText(0, _translate("MainWindow", "base"))
        self.combo_BSA.setItemText(1, _translate("MainWindow", "1x"))
        self.combo_BSA.setItemText(2, _translate("MainWindow", "2x"))
        self.combo_BSA.setItemText(3, _translate("MainWindow", "3x"))
        self.combo_BSA.setItemText(4, _translate("MainWindow", "4x"))
        self.combo_BSA.setItemText(5, _translate("MainWindow", "5x"))
        self.proteinBSAtab.setTabText(self.proteinBSAtab.indexOf(self.tab_10), _translate("MainWindow", "BSA"))
        self.label_18.setText(_translate("MainWindow", "Stop if Id < 2% : "))
        self.radioButton_limit_Id.setText(_translate("MainWindow", "Yes"))
        self.radioButton_no_limit.setText(_translate("MainWindow", "No"))
        self.label_19.setText(_translate("MainWindow", "Measurement Time [mm:ss] : "))
        self.timeProtein.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.check_proteintime.setText(_translate("MainWindow", "Yes"))
        self.label_64.setText(_translate("MainWindow", "Unlimited measurement :"))
        self.label_20.setText(_translate("MainWindow", "Protein Concentration : "))
        self.combo_protein.setItemText(0, _translate("MainWindow", "base"))
        self.combo_protein.setItemText(1, _translate("MainWindow", "conc. -12"))
        self.combo_protein.setItemText(2, _translate("MainWindow", "conc. -11"))
        self.combo_protein.setItemText(3, _translate("MainWindow", "conc. -10"))
        self.combo_protein.setItemText(4, _translate("MainWindow", "conc. -9"))
        self.proteinBSAtab.setTabText(self.proteinBSAtab.indexOf(self.tab_11), _translate("MainWindow", "Protein"))
        self.label_67.setText(_translate("MainWindow", "Stop if Id < 2% : "))
        self.radioButton_limit_Id_2.setText(_translate("MainWindow", "Yes"))
        self.radioButton_no_limit_2.setText(_translate("MainWindow", "No"))
        self.label_68.setText(_translate("MainWindow", "Ionic Solution : "))
        self.label_65.setText(_translate("MainWindow", "Measurement Time [mm:ss] : "))
        self.timeIon.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.label_66.setText(_translate("MainWindow", "Unlimited measurement :"))
        self.check_iontime.setText(_translate("MainWindow", "Yes"))
        self.proteinBSAtab.setTabText(self.proteinBSAtab.indexOf(self.tab_3), _translate("MainWindow", "Ions"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Gate Voltage [V] :"))
        self.label_13.setText(_translate("MainWindow", "Amplitude : "))
        self.label_69.setText(_translate("MainWindow", "Keep @ 0V after meas. :"))
        self.check_vg_turnoff.setText(_translate("MainWindow", "Yes"))
        self.radio_gate_DC.setText(_translate("MainWindow", "DC Signal"))
        self.radio_gate_AC.setText(_translate("MainWindow", "AC Signal"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Drain Voltage [V] :"))
        self.label_14.setText(_translate("MainWindow", "Constant : "))
        self.label_70.setText(_translate("MainWindow", "Keep @ 0V after meas. :"))
        self.check_vd_turnoff.setText(_translate("MainWindow", "Yes"))
        self.Update_online.setText(_translate("MainWindow", "Update Values"))
        self.Start_online.setText(_translate("MainWindow", "Start"))
        self.Stop_online.setText(_translate("MainWindow", "Stop"))
        self.Pause_online.setText(_translate("MainWindow", "Pause"))
        self.Continue_online.setText(_translate("MainWindow", "Continue"))
        self.Output.setTabText(self.Output.indexOf(self.tab_6), _translate("MainWindow", "Online"))
        self.Start_impedance.setText(_translate("MainWindow", "Start"))
        self.Stop_impedance.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "Oscillator amplitude : "))
        self.label_44.setText(_translate("MainWindow", "V"))
        self.label_45.setText(_translate("MainWindow", "Start frequency : "))
        self.label_46.setText(_translate("MainWindow", "Stop frequency : "))
        self.label_47.setText(_translate("MainWindow", "Number of points : "))
        self.label_48.setText(_translate("MainWindow", "Hz"))
        self.label_49.setText(_translate("MainWindow", "Hz"))
        self.label_51.setText(_translate("MainWindow", "Solution :"))
        self.label_50.setText(_translate("MainWindow", "Electrodes : "))
        self.radioButton_FET.setText(_translate("MainWindow", "FET: 10M inputZ"))
        self.radioButton_BJT.setText(_translate("MainWindow", "BJT: 10K input Z"))
        self.label_59.setText(_translate("MainWindow", "Input device:"))
        self.Output.setTabText(self.Output.indexOf(self.impedance), _translate("MainWindow", "Impedance"))
        self.start_voltammetry.setText(_translate("MainWindow", "Start"))
        self.stop_voltammetry.setText(_translate("MainWindow", "Stop"))
        self.label_52.setText(_translate("MainWindow", "Start V [V]"))
        self.label_53.setText(_translate("MainWindow", "Max V [V]"))
        self.label_54.setText(_translate("MainWindow", "Scan rate [mv/s]"))
        self.label_55.setText(_translate("MainWindow", "Cycles"))
        self.label_56.setText(_translate("MainWindow", "Step Size [mV]"))
        self.label_57.setText(_translate("MainWindow", "Current limit [mA]"))
        self.label_58.setText(_translate("MainWindow", "Min V [V]"))
        self.Output.setTabText(self.Output.indexOf(self.cv_tab), _translate("MainWindow", "Voltammetry"))
        self.start_potentialMeas.setText(_translate("MainWindow", "Start"))
        self.stop_potentialMeas.setText(_translate("MainWindow", "Stop"))
        self.label_60.setText(_translate("MainWindow", "Measurement Duration"))
        self.label_61.setText(_translate("MainWindow", "Measurement Delay"))
        self.comboBox_potentiostatChannel.setItemText(0, _translate("MainWindow", "SMU A"))
        self.comboBox_potentiostatChannel.setItemText(1, _translate("MainWindow", "SMU B"))
        self.label_62.setText(_translate("MainWindow", "Potentiostat Channel"))
        self.Output.setTabText(self.Output.indexOf(self.Potentiostat), _translate("MainWindow", "Potentiostat"))
        self.groupBox.setTitle(_translate("MainWindow", "General:"))
        self.CommentName.setText(_translate("MainWindow", "Comments :"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Limits : "))
        self.label_22.setText(_translate("MainWindow", "Gate Current [mA] : "))
        self.label_23.setText(_translate("MainWindow", "Drain Current [mA] : "))
        self.SampleName.setText(_translate("MainWindow", "Sample :"))
        self.DeviceName.setText(_translate("MainWindow", "Device :"))
        self.label_42.setText(_translate("MainWindow", "DAQ time [ms]"))
        self.FilePathName.setText(_translate("MainWindow", "File Path : "))
        self.defaultpath_button.setText(_translate("MainWindow", "Default Path"))
        self.browseFile.setText(_translate("MainWindow", "Browse"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Measurement Unit:"))
        self.radioButton_mu_u2722a.setText(_translate("MainWindow", "U2722A_USB"))
        self.radioButton_mu_k2636.setText(_translate("MainWindow", "K2636_GPIB"))

